#!/usr/bin/env python3

import rclpy
from rclpy.node import Node

from std_msgs.msg import String, Float64

class MoveArm(Node):

    def __init__(self):
        super().__init__('arm_node')
        self.arm1_publisher_ = self.create_publisher(Float64, 'topic', 10)
        timer_period = 0.5  # seconds
        self.timer = self.create_timer(timer_period, self.timer_callback)


    def timer_callback(self):
        ...

def main(args=None):
    rclpy.init(args=args)

    arm_node = MoveArm()

    rclpy.spin(arm_node)

    # Destroy the node explicitly
    # (optional - otherwise it will be done automatically
    # when the garbage collector destroys the node object)
    arm_node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()