#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from builtin_interfaces.msg import Duration

from std_msgs.msg import String, Float64
from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint

class MoveWheel(Node):

    def __init__(self):
        super().__init__('wheel_node')
        self.wheel_publisher_ = self.create_publisher(JointTrajectory, '/wheel_velocity_controller/joint_trajectory', 10)
        self.steer_publisher_ = self.create_publisher(JointTrajectory, '/steer_position_controller/joint_trajectory', 10)
#        self.suspension_publisher_ = self.create_publisher(JointTrajectory, '/wheel_tree_position_controller/joint_trajectory',10)
        timer_period = 0.5  # seconds
        self.timer = self.create_timer(timer_period, self.timer_callback)


    def timer_callback(self):
        #wheel velocities
        traj = JointTrajectory()
        traj.joint_names = ["front_wheel_L_joint",
                            "middle_wheel_L_joint",
                            "back_wheel_L_joint",
                            "front_wheel_R_joint",
                            "middle_wheel_R_joint",
                            "back_wheel_R_joint"]
        
        point = JointTrajectoryPoint()
        point.positions = [0.0,0.0,0.0,0.0,0.0,0.0]
        point.time_from_start = Duration(sec=1)

        traj.points.append(point)
        self.wheel_publisher_.publish(traj)


        #steering wheel
        steer_traj = JointTrajectory()
        steer_traj.joint_names = ["suspension_steer_F_L_joint",
                                    "suspension_steer_B_L_joint",
                                    "suspension_steer_F_R_joint",
                                    "suspension_steer_B_R_joint"]
        
        steer_point = JointTrajectoryPoint()
        steer_point.positions = [1.0,1.0,0.0,0.0]
        steer_point.time_from_start = Duration(sec=1)

        steer_traj.points.append(steer_point)
        self.steer_publisher_.publish(steer_traj)

        # #wheel suspension
        # suspension_traj = JointTrajectory()
        # suspension_traj.joint_names = ["suspension_arm_F_L_joint",
        #                                 "suspension_arm_B_L_joint",
        #                                 "suspension_arm_B2_L_joint",
        #                                 "suspension_arm_F_R_joint",
        #                                 "suspension_arm_B_R_joint",
        #                                 "suspension_arm_B2_R_joint"]

        # suspension_point = JointTrajectoryPoint()
        # suspension_point.positions = [0.0,0.0,0.0,0.0,0.0,0.0]
        # suspension_point.time_from_start = Duration(sec=1)

        # suspension_traj.points.append(suspension_point)
        # self.suspension_publisher_.publish(suspension_traj)

        

def main(args=None):
    rclpy.init(args=args)

    wheel_node = MoveWheel()

    rclpy.spin(wheel_node)

    # Destroy the node explicitly
    # (optional - otherwise it will be done automatically
    # when the garbage collector destroys the node object)
    wheel_node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()