#!/usr/bin/env python3
"""Move the arm to a specific position."""

import rclpy  # type: ignore
from rclpy.node import Node  # type: ignore
from std_srvs.srv import Empty  # type: ignore

from canadarm_common.sim.joint_control import GazeboJointController, IsaacJointController  # type: ignore


class MoveArm(Node):
    """Move the arm to a specific position."""

    def __init__(self):
        super().__init__("arm_node")
        self.open_srv = self.create_service(Empty, "open_arm", self.open_arm_callback)
        self.close_srv = self.create_service(
            Empty, "close_arm", self.close_arm_callback
        )
        self.random_srv = self.create_service(
            Empty, "random_arm", self.random_arm_callback
        )

        # Set sim parameter
        self.declare_parameter(
            "environment",
            rclpy.Parameter.Type.STRING,
        )

        self._environment = (
            self.get_parameter("environment").get_parameter_value().string_value
        )

        if self._environment == "gazebosim":
            self._controller = GazeboJointController(self)
        elif self._environment == "isaacsim":
            self._controller = IsaacJointController(self)
        self._logger.info(f"Using {self._environment} environment")

        self._joint_names = [
            "Base_Joint",
            "Shoulder_Roll",
            "Shoulder_Yaw",
            "Elbow_Pitch",
            "Wrist_Pitch",
            "Wrist_Yaw",
            "Wrist_Roll",
        ]
        self._open_positions = [0.0, 0.0, 0.0, -3.1416, 0.0, 0.0, 0.0]
        self._close_positions = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        self._random_positions = [1.0, -1.5, 2.0, -3.2, 0.8, 0.5, -1.0]

    def open_arm_callback(self, request, response):  # pylint: disable=unused-argument
        """Open the arm."""
        self._controller.set_joint_states(self._joint_names, self._open_positions)

        return response

    def close_arm_callback(self, request, response):  # pylint: disable=unused-argument
        """Close the arm."""
        self._controller.set_joint_states(self._joint_names, self._close_positions)

        return response

    def random_arm_callback(self, request, response):  # pylint: disable=unused-argument
        """Move the arm to a random position."""
        self._controller.set_joint_states(self._joint_names, self._random_positions)

        return response


def main(args=None):
    """Main function."""
    rclpy.init(args=args)

    arm_node = MoveArm()

    rclpy.spin(arm_node)
    # Destroy the node explicitly
    # (optional - otherwise it will be done automatically
    # when the garbage collector destroys the node object)
    arm_node.destroy_node()
    rclpy.shutdown()


if __name__ == "__main__":
    main()
