use pyo3::prelude::*;
mod macros;

mod envs;

/// Name of the root Python module generated by this Rust extension module.
const PYTHON_MODULE_NAME: &str = "spaceros_procgen_envs._rs";

#[pymodule]
fn _rs(m: &Bound<'_, PyModule>) -> PyResult<()> {
    envs::register(m)?;
    Ok(())
}
