arm_joint_trajectory_controller:
  joints:
    - arm_01_joint
    - arm_02_joint
    - arm_03_joint
    - arm_04_joint
    - arm_tools_joint
  # interface_name: position  # NOT supported currently
  # command_interfaces:
  #   - position
  # state_interfaces:
  #   - position
  #   - velocity

mast_joint_trajectory_controller:
  joints:
    - mast_p_joint
    - mast_02_joint
    - mast_cameras_joint
  # interface_name: position  # NOT supported currently
  # command_interfaces:
  #   - position
  # state_interfaces:
  #   - position
  #   - velocity

wheel_velocity_controller:
  joints:
    - front_wheel_L_joint
    - middle_wheel_L_joint
    - back_wheel_L_joint
    - front_wheel_R_joint
    - middle_wheel_R_joint
    - back_wheel_R_joint
  # interface_name: velocity  # NOT supported currently


steer_position_controller:
  joints:
    - suspension_steer_F_L_joint
    - suspension_steer_B_L_joint
    - suspension_steer_F_R_joint
    - suspension_steer_B_R_joint
  # interface_name: position  # NOT supported currently
  # command_interfaces:
  #   - position
  # state_interfaces:
  #   - position
  #   - velocity

wheel_tree_position_controller:
  joints:
    - suspension_arm_F_L_joint
    - suspension_arm_B_L_joint
    - suspension_arm_F_R_joint
    - suspension_arm_B_R_joint
  # command_interfaces:  # NOT supported currently
  #   - effort
  # state_interfaces:
  #   - position
  #   - velocity
  #   - effort
  # gains: # Currently, not being applied through code, they are set directly in ISAAC
  #   suspension_arm_F_L_joint:
  #     p: 2200.0
  #     i: 10.0
  #     d: 10.0
  #   suspension_arm_B_L_joint:
  #     p: 4200.0
  #     i: 10.0
  #     d: 10.0
  #   suspension_arm_F_R_joint:
  #     p: 2200.0
  #     i: 10.0
  #     d: 10.0
  #   suspension_arm_B_R_joint:
  #     p: 4200.0
  #     i: 10.0
  #     d: 10.0
  # enable:
  #   suspension_arm_F_L_joint:
  #     status: 1
  #   suspension_arm_B_L_joint:
  #     status: 1
  #   suspension_arm_F_R_joint:
  #     status: 1
  #   suspension_arm_B_R_joint:
  #     status: 1
