indent-width = 4
line-length = 120
target-version = "py310"

[lint]
# Matches _, __, and _var but not _var_
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
fixable = ["ALL"]
ignore = [
  "D100",
  "D203",
  "D213",
  "D400",
  "D401",
  "D415",
  "PLR0912",
  "PLR0913",
  "PLR0915",
  "RUF012"
]
select = ["E", "W", "F", "I", "B", "D", "RET", "RUF", "PL", "PIE", "FLY"]
unfixable = []
