#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from builtin_interfaces.msg import Duration

from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint
from std_srvs.srv import Empty


class MastCamera(Node):

    def __init__(self):
        super().__init__('mast_node')
        self.mast_publisher_ = self.create_publisher(JointTrajectory, '/mast_camera_joint_trajectory_controller/joint_trajectory', 10)
        self.camera_center_srv = self.create_service(Empty, 'camera_center', self.camera_center_callback)
        self.camera_rotate_srv = self.create_service(Empty, 'camera_rotate', self.camera_rotate_callback)

    def camera_center_callback(self, request, response):
        traj = JointTrajectory()
        traj.joint_names = ["mast_head_pivot_joint", "mast_camera_joint"]

        point = JointTrajectoryPoint()
        point.positions = [0.0, 0.7854]
        point.time_from_start = Duration(sec=1)

        traj.points.append(point)
        self.mast_publisher_.publish(traj)
        return response

    def camera_rotate_callback(self, request, response):
        traj = JointTrajectory()
        traj.joint_names = ["mast_head_pivot_joint", "mast_camera_joint"]

        point1 = JointTrajectoryPoint()
        point1.positions = [0.0, 0.7854]
        point1.time_from_start = Duration(sec=1)
        traj.points.append(point1)

        point2 = JointTrajectoryPoint()
        point2.positions = [-3.49, 0.0]
        point2.time_from_start = Duration(sec=3)
        traj.points.append(point2)

        point3 = JointTrajectoryPoint()
        point3.positions = [0.0, 0.7854]
        point3.time_from_start = Duration(sec=6)
        traj.points.append(point3)

        point4 = JointTrajectoryPoint()
        point4.positions = [3.49, 0.0]
        point4.time_from_start = Duration(sec=9)
        traj.points.append(point4)

        self.mast_publisher_.publish(traj)
        return response


def main(args=None):
    rclpy.init(args=args)

    mast_node = MastCamera()

    rclpy.spin(mast_node)

    # Destroy the node explicitly
    # (optional - otherwise it will be done automatically
    # when the garbage collector destroys the node object)
    mast_node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
