robot_1:
  controller_manager:
    ros__parameters:
      update_rate: 100  # Hz

      forward_velocity_controller:
        type: forward_command_controller/ForwardCommandController
        
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

  forward_velocity_controller:
    ros__parameters:
      joints:
        - robot_1_Solar2_joint
        - robot_1_Solar1_joint
        # - robot_1_right_back_wheel_joint
        # - robot_1_right_front_wheel_joint
      interface_name: velocity
      command_interfaces:
        - velocity
      state_interfaces:
        - velocity
