controller_manager:
  ros__parameters:
    update_rate: 100

    mast_camera_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    steer_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


mast_camera_joint_trajectory_controller:
  ros__parameters:
    joints:
      - mast_head_pivot_joint
      - mast_camera_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

wheel_velocity_controller:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - rear_left_wheel_joint
      - front_right_wheel_joint
      - rear_right_wheel_joint
    interface_name: velocity

steer_position_controller:
  ros__parameters:
    joints:
      - front_left_wheel_axle_joint
      - rear_left_wheel_axle_joint
      - front_right_wheel_axle_joint
      - rear_right_wheel_axle_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
