/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: RACS2Bridge_geometry_msgs.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "RACS2Bridge_geometry_msgs.pb-c.h"
void   racs2_bridge_geometry_msgs__vector3__init
                     (RACS2BridgeGeometryMsgsVector3         *message)
{
  static const RACS2BridgeGeometryMsgsVector3 init_value = RACS2_BRIDGE_GEOMETRY_MSGS__VECTOR3__INIT;
  *message = init_value;
}
size_t racs2_bridge_geometry_msgs__vector3__get_packed_size
                     (const RACS2BridgeGeometryMsgsVector3 *message)
{
  assert(message->base.descriptor == &racs2_bridge_geometry_msgs__vector3__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t racs2_bridge_geometry_msgs__vector3__pack
                     (const RACS2BridgeGeometryMsgsVector3 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &racs2_bridge_geometry_msgs__vector3__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t racs2_bridge_geometry_msgs__vector3__pack_to_buffer
                     (const RACS2BridgeGeometryMsgsVector3 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &racs2_bridge_geometry_msgs__vector3__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RACS2BridgeGeometryMsgsVector3 *
       racs2_bridge_geometry_msgs__vector3__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RACS2BridgeGeometryMsgsVector3 *)
     protobuf_c_message_unpack (&racs2_bridge_geometry_msgs__vector3__descriptor,
                                allocator, len, data);
}
void   racs2_bridge_geometry_msgs__vector3__free_unpacked
                     (RACS2BridgeGeometryMsgsVector3 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &racs2_bridge_geometry_msgs__vector3__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   racs2_bridge_geometry_msgs__twist__init
                     (RACS2BridgeGeometryMsgsTwist         *message)
{
  static const RACS2BridgeGeometryMsgsTwist init_value = RACS2_BRIDGE_GEOMETRY_MSGS__TWIST__INIT;
  *message = init_value;
}
size_t racs2_bridge_geometry_msgs__twist__get_packed_size
                     (const RACS2BridgeGeometryMsgsTwist *message)
{
  assert(message->base.descriptor == &racs2_bridge_geometry_msgs__twist__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t racs2_bridge_geometry_msgs__twist__pack
                     (const RACS2BridgeGeometryMsgsTwist *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &racs2_bridge_geometry_msgs__twist__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t racs2_bridge_geometry_msgs__twist__pack_to_buffer
                     (const RACS2BridgeGeometryMsgsTwist *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &racs2_bridge_geometry_msgs__twist__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RACS2BridgeGeometryMsgsTwist *
       racs2_bridge_geometry_msgs__twist__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RACS2BridgeGeometryMsgsTwist *)
     protobuf_c_message_unpack (&racs2_bridge_geometry_msgs__twist__descriptor,
                                allocator, len, data);
}
void   racs2_bridge_geometry_msgs__twist__free_unpacked
                     (RACS2BridgeGeometryMsgsTwist *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &racs2_bridge_geometry_msgs__twist__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   racs2_bridge_geometry_msgs__init
                     (RACS2BridgeGeometryMsgs         *message)
{
  static const RACS2BridgeGeometryMsgs init_value = RACS2_BRIDGE_GEOMETRY_MSGS__INIT;
  *message = init_value;
}
size_t racs2_bridge_geometry_msgs__get_packed_size
                     (const RACS2BridgeGeometryMsgs *message)
{
  assert(message->base.descriptor == &racs2_bridge_geometry_msgs__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t racs2_bridge_geometry_msgs__pack
                     (const RACS2BridgeGeometryMsgs *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &racs2_bridge_geometry_msgs__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t racs2_bridge_geometry_msgs__pack_to_buffer
                     (const RACS2BridgeGeometryMsgs *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &racs2_bridge_geometry_msgs__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RACS2BridgeGeometryMsgs *
       racs2_bridge_geometry_msgs__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RACS2BridgeGeometryMsgs *)
     protobuf_c_message_unpack (&racs2_bridge_geometry_msgs__descriptor,
                                allocator, len, data);
}
void   racs2_bridge_geometry_msgs__free_unpacked
                     (RACS2BridgeGeometryMsgs *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &racs2_bridge_geometry_msgs__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor racs2_bridge_geometry_msgs__vector3__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(RACS2BridgeGeometryMsgsVector3, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(RACS2BridgeGeometryMsgsVector3, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(RACS2BridgeGeometryMsgsVector3, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned racs2_bridge_geometry_msgs__vector3__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange racs2_bridge_geometry_msgs__vector3__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor racs2_bridge_geometry_msgs__vector3__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RACS2Bridge_geometry_msgs_Vector3",
  "RACS2BridgeGeometryMsgsVector3",
  "RACS2BridgeGeometryMsgsVector3",
  "",
  sizeof(RACS2BridgeGeometryMsgsVector3),
  3,
  racs2_bridge_geometry_msgs__vector3__field_descriptors,
  racs2_bridge_geometry_msgs__vector3__field_indices_by_name,
  1,  racs2_bridge_geometry_msgs__vector3__number_ranges,
  (ProtobufCMessageInit) racs2_bridge_geometry_msgs__vector3__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor racs2_bridge_geometry_msgs__twist__field_descriptors[2] =
{
  {
    "linear",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RACS2BridgeGeometryMsgsTwist, linear),
    &racs2_bridge_geometry_msgs__vector3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "angular",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(RACS2BridgeGeometryMsgsTwist, angular),
    &racs2_bridge_geometry_msgs__vector3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned racs2_bridge_geometry_msgs__twist__field_indices_by_name[] = {
  1,   /* field[1] = angular */
  0,   /* field[0] = linear */
};
static const ProtobufCIntRange racs2_bridge_geometry_msgs__twist__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor racs2_bridge_geometry_msgs__twist__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RACS2Bridge_geometry_msgs_Twist",
  "RACS2BridgeGeometryMsgsTwist",
  "RACS2BridgeGeometryMsgsTwist",
  "",
  sizeof(RACS2BridgeGeometryMsgsTwist),
  2,
  racs2_bridge_geometry_msgs__twist__field_descriptors,
  racs2_bridge_geometry_msgs__twist__field_indices_by_name,
  1,  racs2_bridge_geometry_msgs__twist__number_ranges,
  (ProtobufCMessageInit) racs2_bridge_geometry_msgs__twist__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor racs2_bridge_geometry_msgs__field_descriptors[26] =
{
  {
    "accel_with_covariance_data",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_accel_with_covariance_data),
    offsetof(RACS2BridgeGeometryMsgs, accel_with_covariance_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accel_with_covariance_stamped_data",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_accel_with_covariance_stamped_data),
    offsetof(RACS2BridgeGeometryMsgs, accel_with_covariance_stamped_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "point_stamped_data",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_point_stamped_data),
    offsetof(RACS2BridgeGeometryMsgs, point_stamped_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inertia_stamped_data",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_inertia_stamped_data),
    offsetof(RACS2BridgeGeometryMsgs, inertia_stamped_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quaternion_stamped_data",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_quaternion_stamped_data),
    offsetof(RACS2BridgeGeometryMsgs, quaternion_stamped_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transform_stamped_data",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_transform_stamped_data),
    offsetof(RACS2BridgeGeometryMsgs, transform_stamped_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inertia_data",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_inertia_data),
    offsetof(RACS2BridgeGeometryMsgs, inertia_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pose_with_covariance_data",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_pose_with_covariance_data),
    offsetof(RACS2BridgeGeometryMsgs, pose_with_covariance_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "twist_covariance_stamped_data",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_twist_covariance_stamped_data),
    offsetof(RACS2BridgeGeometryMsgs, twist_covariance_stamped_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wrench_data",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_wrench_data),
    offsetof(RACS2BridgeGeometryMsgs, wrench_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accel_data",
    11,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_accel_data),
    offsetof(RACS2BridgeGeometryMsgs, accel_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pose_with_covariance_stamped_data",
    12,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_pose_with_covariance_stamped_data),
    offsetof(RACS2BridgeGeometryMsgs, pose_with_covariance_stamped_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accele_stamped_data",
    13,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_accele_stamped_data),
    offsetof(RACS2BridgeGeometryMsgs, accele_stamped_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transform_data",
    14,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_transform_data),
    offsetof(RACS2BridgeGeometryMsgs, transform_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "point_data",
    15,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_point_data),
    offsetof(RACS2BridgeGeometryMsgs, point_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "polygon_stamped_dta",
    16,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_polygon_stamped_dta),
    offsetof(RACS2BridgeGeometryMsgs, polygon_stamped_dta),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pose_array_data",
    17,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_pose_array_data),
    offsetof(RACS2BridgeGeometryMsgs, pose_array_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vector3_stamped_data",
    18,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_vector3_stamped_data),
    offsetof(RACS2BridgeGeometryMsgs, vector3_stamped_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pose_stamped_data",
    19,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_pose_stamped_data),
    offsetof(RACS2BridgeGeometryMsgs, pose_stamped_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "polygon_data",
    20,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_polygon_data),
    offsetof(RACS2BridgeGeometryMsgs, polygon_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "queaternion_data",
    21,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_queaternion_data),
    offsetof(RACS2BridgeGeometryMsgs, queaternion_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "point32_data",
    22,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_point32_data),
    offsetof(RACS2BridgeGeometryMsgs, point32_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "twist_with_covariance_data",
    23,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_twist_with_covariance_data),
    offsetof(RACS2BridgeGeometryMsgs, twist_with_covariance_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pose_data",
    24,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_pose_data),
    offsetof(RACS2BridgeGeometryMsgs, pose_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "twist_stamped_data",
    25,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_twist_stamped_data),
    offsetof(RACS2BridgeGeometryMsgs, twist_stamped_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pose_2d_data",
    26,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(RACS2BridgeGeometryMsgs, n_pose_2d_data),
    offsetof(RACS2BridgeGeometryMsgs, pose_2d_data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned racs2_bridge_geometry_msgs__field_indices_by_name[] = {
  10,   /* field[10] = accel_data */
  0,   /* field[0] = accel_with_covariance_data */
  1,   /* field[1] = accel_with_covariance_stamped_data */
  12,   /* field[12] = accele_stamped_data */
  6,   /* field[6] = inertia_data */
  3,   /* field[3] = inertia_stamped_data */
  21,   /* field[21] = point32_data */
  14,   /* field[14] = point_data */
  2,   /* field[2] = point_stamped_data */
  19,   /* field[19] = polygon_data */
  15,   /* field[15] = polygon_stamped_dta */
  25,   /* field[25] = pose_2d_data */
  16,   /* field[16] = pose_array_data */
  23,   /* field[23] = pose_data */
  18,   /* field[18] = pose_stamped_data */
  7,   /* field[7] = pose_with_covariance_data */
  11,   /* field[11] = pose_with_covariance_stamped_data */
  4,   /* field[4] = quaternion_stamped_data */
  20,   /* field[20] = queaternion_data */
  13,   /* field[13] = transform_data */
  5,   /* field[5] = transform_stamped_data */
  8,   /* field[8] = twist_covariance_stamped_data */
  24,   /* field[24] = twist_stamped_data */
  22,   /* field[22] = twist_with_covariance_data */
  17,   /* field[17] = vector3_stamped_data */
  9,   /* field[9] = wrench_data */
};
static const ProtobufCIntRange racs2_bridge_geometry_msgs__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 26 }
};
const ProtobufCMessageDescriptor racs2_bridge_geometry_msgs__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RACS2Bridge_geometry_msgs",
  "RACS2BridgeGeometryMsgs",
  "RACS2BridgeGeometryMsgs",
  "",
  sizeof(RACS2BridgeGeometryMsgs),
  26,
  racs2_bridge_geometry_msgs__field_descriptors,
  racs2_bridge_geometry_msgs__field_indices_by_name,
  1,  racs2_bridge_geometry_msgs__number_ranges,
  (ProtobufCMessageInit) racs2_bridge_geometry_msgs__init,
  NULL,NULL,NULL    /* reserved[123] */
};
