/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: RACS2Bridge_geometry_msgs.proto */

#ifndef PROTOBUF_C_RACS2Bridge_5fgeometry_5fmsgs_2eproto__INCLUDED
#define PROTOBUF_C_RACS2Bridge_5fgeometry_5fmsgs_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _RACS2BridgeGeometryMsgsVector3 RACS2BridgeGeometryMsgsVector3;
typedef struct _RACS2BridgeGeometryMsgsTwist RACS2BridgeGeometryMsgsTwist;
typedef struct _RACS2BridgeGeometryMsgs RACS2BridgeGeometryMsgs;


/* --- enums --- */


/* --- messages --- */

struct  _RACS2BridgeGeometryMsgsVector3
{
  ProtobufCMessage base;
  /*
   * -- geometry_msgs/Vector3 ----------------------------
   */
  double x;
  double y;
  double z;
};
#define RACS2_BRIDGE_GEOMETRY_MSGS__VECTOR3__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&racs2_bridge_geometry_msgs__vector3__descriptor) \
    , 0, 0, 0 }


struct  _RACS2BridgeGeometryMsgsTwist
{
  ProtobufCMessage base;
  /*
   * -- geometry_msgs/Twist ------------------------------
   */
  RACS2BridgeGeometryMsgsVector3 *linear;
  RACS2BridgeGeometryMsgsVector3 *angular;
};
#define RACS2_BRIDGE_GEOMETRY_MSGS__TWIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&racs2_bridge_geometry_msgs__twist__descriptor) \
    , NULL, NULL }


struct  _RACS2BridgeGeometryMsgs
{
  ProtobufCMessage base;
  /*
   * -- geometry_msgs/AccelWithCovariance ----------------
   */
  size_t n_accel_with_covariance_data;
  float *accel_with_covariance_data;
  /*
   * -- geometry_msgs/AccelWithCovarianceStamped ---------
   */
  size_t n_accel_with_covariance_stamped_data;
  float *accel_with_covariance_stamped_data;
  /*
   * -- geometry_msgs/PointStamped -----------------------
   */
  size_t n_point_stamped_data;
  float *point_stamped_data;
  /*
   * -- geometry_msgs/InertiaStamped ---------------------
   */
  size_t n_inertia_stamped_data;
  float *inertia_stamped_data;
  /*
   * -- geometry_msgs/QuaternionStamped ------------------
   */
  size_t n_quaternion_stamped_data;
  float *quaternion_stamped_data;
  /*
   * -- geometry_msgs/TransformStamped -------------------
   */
  size_t n_transform_stamped_data;
  float *transform_stamped_data;
  /*
   * -- geometry_msgs/Inertia ----------------------------
   */
  size_t n_inertia_data;
  float *inertia_data;
  /*
   * -- geometry_msgs/PoseWithCovariance -----------------
   */
  size_t n_pose_with_covariance_data;
  float *pose_with_covariance_data;
  /*
   * -- geometry_msgs/TwistWithCovarianceStamped ---------
   */
  size_t n_twist_covariance_stamped_data;
  float *twist_covariance_stamped_data;
  /*
   * -- geometry_msgs/Wrench -----------------------------
   */
  size_t n_wrench_data;
  float *wrench_data;
  /*
   * -- geometry_msgs/Accel ------------------------------
   */
  size_t n_accel_data;
  float *accel_data;
  /*
   * -- geometry_msgs/PoseWithCovarianceStamped ----------
   */
  size_t n_pose_with_covariance_stamped_data;
  float *pose_with_covariance_stamped_data;
  /*
   * -- geometry_msgs/AccelStamped -----------------------
   */
  size_t n_accele_stamped_data;
  float *accele_stamped_data;
  /*
   * -- geometry_msgs/Transform --------------------------
   */
  size_t n_transform_data;
  float *transform_data;
  /*
   * -- geometry_msgs/Point ------------------------------
   */
  size_t n_point_data;
  float *point_data;
  /*
   * -- geometry_msgs/PolygonStamped ---------------------
   */
  size_t n_polygon_stamped_dta;
  float *polygon_stamped_dta;
  /*
   * -- geometry_msgs/PoseArray --------------------------
   */
  size_t n_pose_array_data;
  float *pose_array_data;
  /*
   * -- geometry_msgs/Vector3Stamped ---------------------
   */
  size_t n_vector3_stamped_data;
  float *vector3_stamped_data;
  /*
   * -- geometry_msgs/PoseStamped ------------------------
   */
  size_t n_pose_stamped_data;
  float *pose_stamped_data;
  /*
   * -- geometry_msgs/Polygon ----------------------------
   */
  size_t n_polygon_data;
  float *polygon_data;
  /*
   * -- geometry_msgs/Quaternion -------------------------
   */
  size_t n_queaternion_data;
  float *queaternion_data;
  /*
   * -- geometry_msgs/Point32 ----------------------------
   */
  size_t n_point32_data;
  float *point32_data;
  /*
   * -- geometry_msgs/TwistWithCovariance ----------------
   */
  size_t n_twist_with_covariance_data;
  float *twist_with_covariance_data;
  /*
   * -- geometry_msgs/Pose -------------------------------
   */
  size_t n_pose_data;
  float *pose_data;
  /*
   * -- geometry_msgs/TwistStamped -----------------------
   */
  size_t n_twist_stamped_data;
  float *twist_stamped_data;
  /*
   * -- geometry_msgs/Pose2D -----------------------------
   */
  size_t n_pose_2d_data;
  float *pose_2d_data;
};
#define RACS2_BRIDGE_GEOMETRY_MSGS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&racs2_bridge_geometry_msgs__descriptor) \
    , 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL }


/* RACS2BridgeGeometryMsgsVector3 methods */
void   racs2_bridge_geometry_msgs__vector3__init
                     (RACS2BridgeGeometryMsgsVector3         *message);
size_t racs2_bridge_geometry_msgs__vector3__get_packed_size
                     (const RACS2BridgeGeometryMsgsVector3   *message);
size_t racs2_bridge_geometry_msgs__vector3__pack
                     (const RACS2BridgeGeometryMsgsVector3   *message,
                      uint8_t             *out);
size_t racs2_bridge_geometry_msgs__vector3__pack_to_buffer
                     (const RACS2BridgeGeometryMsgsVector3   *message,
                      ProtobufCBuffer     *buffer);
RACS2BridgeGeometryMsgsVector3 *
       racs2_bridge_geometry_msgs__vector3__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   racs2_bridge_geometry_msgs__vector3__free_unpacked
                     (RACS2BridgeGeometryMsgsVector3 *message,
                      ProtobufCAllocator *allocator);
/* RACS2BridgeGeometryMsgsTwist methods */
void   racs2_bridge_geometry_msgs__twist__init
                     (RACS2BridgeGeometryMsgsTwist         *message);
size_t racs2_bridge_geometry_msgs__twist__get_packed_size
                     (const RACS2BridgeGeometryMsgsTwist   *message);
size_t racs2_bridge_geometry_msgs__twist__pack
                     (const RACS2BridgeGeometryMsgsTwist   *message,
                      uint8_t             *out);
size_t racs2_bridge_geometry_msgs__twist__pack_to_buffer
                     (const RACS2BridgeGeometryMsgsTwist   *message,
                      ProtobufCBuffer     *buffer);
RACS2BridgeGeometryMsgsTwist *
       racs2_bridge_geometry_msgs__twist__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   racs2_bridge_geometry_msgs__twist__free_unpacked
                     (RACS2BridgeGeometryMsgsTwist *message,
                      ProtobufCAllocator *allocator);
/* RACS2BridgeGeometryMsgs methods */
void   racs2_bridge_geometry_msgs__init
                     (RACS2BridgeGeometryMsgs         *message);
size_t racs2_bridge_geometry_msgs__get_packed_size
                     (const RACS2BridgeGeometryMsgs   *message);
size_t racs2_bridge_geometry_msgs__pack
                     (const RACS2BridgeGeometryMsgs   *message,
                      uint8_t             *out);
size_t racs2_bridge_geometry_msgs__pack_to_buffer
                     (const RACS2BridgeGeometryMsgs   *message,
                      ProtobufCBuffer     *buffer);
RACS2BridgeGeometryMsgs *
       racs2_bridge_geometry_msgs__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   racs2_bridge_geometry_msgs__free_unpacked
                     (RACS2BridgeGeometryMsgs *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*RACS2BridgeGeometryMsgsVector3_Closure)
                 (const RACS2BridgeGeometryMsgsVector3 *message,
                  void *closure_data);
typedef void (*RACS2BridgeGeometryMsgsTwist_Closure)
                 (const RACS2BridgeGeometryMsgsTwist *message,
                  void *closure_data);
typedef void (*RACS2BridgeGeometryMsgs_Closure)
                 (const RACS2BridgeGeometryMsgs *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor racs2_bridge_geometry_msgs__vector3__descriptor;
extern const ProtobufCMessageDescriptor racs2_bridge_geometry_msgs__twist__descriptor;
extern const ProtobufCMessageDescriptor racs2_bridge_geometry_msgs__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_RACS2Bridge_5fgeometry_5fmsgs_2eproto__INCLUDED */
