[package]
name = "spaceros_procgen_envs"
description.workspace = true
categories.workspace = true
keywords.workspace = true
readme.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
figment = { workspace = true }
pyo3 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
serde_yaml = { workspace = true, optional = true }
thiserror = { workspace = true }
toml = { workspace = true, optional = true }

[features]
default = ["yaml"]
json = ["dep:serde_json", "figment/json"]
toml = ["dep:toml", "figment/toml"]
yaml = ["dep:serde_yaml", "figment/yaml"]
